# Generated by Django 3.1.4 on 2021-01-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201228_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='project',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='project',
            new_name='category',
        ),
    ]
