# Generated by Django 3.1.4 on 2021-01-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210103_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='carbon_calculator_type',
            field=models.CharField(blank=True, choices=[('Calculette Nucléaire', 'Calculette Nucléaire'), ('Calculette Datacenter', 'Calculette Datacenter'), ('Calculette Retail et Logistique', 'Calculette Retail et Logistique'), ('Calculette Tertiaire', 'Calculette Tertiaire')], default='', max_length=100),
        ),
    ]
