# Generated by Django 3.1.4 on 2021-01-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210121_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Bureaux', 'Bureaux'), ('Hopital', 'Hopital')], default='', max_length=150)),
                ('cvc_value', models.IntegerField(blank=True, default=0)),
                ('plb_value', models.IntegerField(blank=True, default=0)),
                ('cfo_value', models.IntegerField(blank=True, default=0)),
                ('cfa_value', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
