# Generated by Django 3.1.4 on 2021-01-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_calculationconstants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalculationConstants',
            new_name='CalculationConstant',
        ),
    ]
