# Generated by Django 3.1.4 on 2021-01-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210122_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationconstant',
            name='type',
            field=models.CharField(blank=True, choices=[('Bureaux', 'Bureaux'), ('Hopital', 'Hopital'), ('Commerce', 'Commerce'), ('EHPAD', 'EHPAD'), ('Hotel', 'Hotel'), ('Restauration', 'Restauration'), ('Accueil petite enfance', 'Accueil petite enfance'), ('Gymnase', 'Gymnase'), ('Enseignement', 'Enseignement')], default='', max_length=150),
        ),
    ]
