# Generated by Django 3.1.4 on 2021-01-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20210128_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='carbon_calculator_type',
            field=models.CharField(choices=[('Calculette Nucléaire', 'Calculette Nucléaire'), ('Calculette Datacenter', 'Calculette Datacenter'), ('Calculette Retail et Logistique', 'Calculette Retail et Logistique'), ('Calculette Tertiaire', 'Calculette Tertiaire')], default='', max_length=100),
        ),
    ]
