# Generated by Django 3.1.4 on 2021-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210128_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('Nouvelles installations nucléaires et infrastructures énergétiques', 'Nouvelles installations nucléaires et infrastructures énergétiques'), ('Infrastructures de transport', 'Infrastructures de transport'), ('Défense et sécurité nationale', 'Défense et sécurité nationale'), ('Industrie de transformation', 'Industrie de transformation'), ('Industrie des procédés', 'Industrie des procédés'), ('Datacenter', 'Datacenter'), ('Retail et logistique', 'Retail et logistique'), ('Global Facility Management', 'Global Facility Management'), ('Solutions digitales', 'Solutions digitales'), ('Tertiaire', 'Tertiaire')], default='', max_length=150),
        ),
    ]
