# Generated by Django 3.1.4 on 2021-02-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20210205_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='link',
        ),
        migrations.AddField(
            model_name='news',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
