export const DATA_LIST_FETCH = 'DATA_LIST_FETCH';
export const DATA_LIST_SUCCESS = 'DATA_LIST_SUCCESS';
export const DATA_LIST_ERROR = 'DATA_LIST_ERROR';
export const DATA_LIST_ACCESS_DENIED = 'DATA_LIST_ACCESS_DENIED';